theme: jekyll-theme-minimal
title: Ronghao Ni
logo: "/logo.jpeg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Independent and collaborative
  <br><br>
  Email: nironghao@gmail.com, ronghaon@andrew.cmu.edu
  <br><br>
  <a href="https://scholar.google.com/citations?user=Gy9bWVIAAAAJ">View My Google Scholar Profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/ronghao-ni/">View My LinkedIn Profile</a> 
google_analytics: UA-117417162-1

# ---------------- #
#      Comments    #
# ---------------- #
comments_provider: gitalk
gitalk:
    owner: rogerni
    repo: rogerni.github.io
    clientID: 9565c34a0c4e9a86361e
    clientSecret: 72f289b624fbe6682e675f6464b943b6cac30eb1
